############### Stem config ###############

stem.name = "ResStem"
stage.name = "ResResidualBlock"

############### Stage config ###############

stage.stage_strides = [1, 2, 2, 2]
stage.stage_widths = [32, 64, 128, 256]
stage.stage_depths = [2, 2, 2, 2]
stage.trans_block_name = "ResBasicBlock"

############### Head config ###############

head.name = "ResConvHead"
head.num_classes = 10