############### System config ###############

task = "classification"
random_seed = 42
num_gpus = 1
report_dir = ""

############### Model config ###############

model_cfg_path = ""

############### Runner config ###############

mode = "train"
num_epochs = 10