############### Task Configuration ###############

task = "classification"

############### Environment Configuration ###############

random_seed = 13
num_gpus = 1
report_dir = ""

############### Model Configuration ###############

backbone_cfg_path = ""
neck_cfg_path = ""
head_cfg_path = ""
num_classes = 10
class_names = []

############### Optimizer Configuration ###############



############### Runner Configuration ###############

mode = "train"
num_epochs = 10


############### Dataset Configuration ###############

train_dataset_type = "img_folder"
train_dataset_paths = [""]

val_dataset_type = "csv_annotation"
val_dataset_paths = [""]

test_dataset_type = "pickle"
test_dataset_paths = [""]

inference_dataset_type = "img_folder"
inference_dataset_paths = [""]


############### Data Augmentation Configuration ###############